"""Create response_validations table

Revision ID: 7ce961eff140
Revises: 91317f5e7bb1
Create Date: 2025-10-20 19:23:30.205174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce961eff140'
down_revision: Union[str, None] = '91317f5e7bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('validator_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('criteria_scores', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('validator_version', sa.String(length=50), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_validations_id'), 'response_validations', ['id'], unique=False)
    op.create_index(op.f('ix_response_validations_response_id'), 'response_validations', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_validations_response_id'), table_name='response_validations')
    op.drop_index(op.f('ix_response_validations_id'), table_name='response_validations')
    op.drop_table('response_validations')
    # ### end Alembic commands ###
