"""Create agent_prompts table

Revision ID: 91317f5e7bb1
Revises: fe5212628a8c
Create Date: 2025-10-20 17:29:42.671138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91317f5e7bb1'
down_revision: Union[str, None] = 'fe5212628a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_prompts_agent_name'), 'agent_prompts', ['agent_name'], unique=True)
    op.create_index(op.f('ix_agent_prompts_id'), 'agent_prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_prompts_id'), table_name='agent_prompts')
    op.drop_index(op.f('ix_agent_prompts_agent_name'), table_name='agent_prompts')
    op.drop_table('agent_prompts')
    # ### end Alembic commands ###
